package com.koushik;

import java.util.List;

/**
 * A thin RAG “agent” that follows the same prompt template you saw in the Python example:
 *
 *   You are a helpful AI assistant. Use ONLY the provided context to answer the user question.
 *   …
 *
 * The class is deliberately stateless except for the services it wraps, which makes it easy
 * to reuse in a web server, a CLI, or a chatbot.
 */
public class RagAgent {

    private static final String PROMPT_TEMPLATE =
            "You are a helpful AI assistant. Use ONLY the provided context to answer the user question.\n" +
            "If the answer is not contained in the context, politely say you don’t know.\n\n" +
            "<context>\n" +
            "%s\n" +      // placeholder for retrieved docs
            "</context>\n\n" +
            "Question: %s\n" +
            "Answer (in plain text, no markdown unless explicitly asked):";

    private final Retriever retriever;
    private final EmbeddingService embeddingService;
    private final OllamaChatClient chatClient;
    private final int topK;

    /**
     * @param retriever        the vector store
     * @param embeddingService the same service used by the retriever (so we can embed the query)
     * @param chatClient       Ollama client
     * @param topK             how many docs to feed the LLM with
     */
    public RagAgent(Retriever retriever,
                    EmbeddingService embeddingService,
                    OllamaChatClient chatClient,
                    int topK) {
        this.retriever = retriever;
        this.embeddingService = embeddingService;
        this.chatClient = chatClient;
        this.topK = topK;
    }

    /**
     * Main entry point – given a natural‑language question, returns the LLM answer.
     *
     * @param question the user query
     * @return answer generated by the LLM
     * @throws Exception if anything goes wrong (embedding, retrieval, HTTP)
     */
    public String answer(String question) throws Exception {
        // 1️⃣ Retrieve top‑k docs
        List<String> docs = retriever.retrieve(question, topK, embeddingService);
        String retrievedText = String.join("\n---\n", docs);   // separate docs with a line

        // 2️⃣ Build the prompt
        String prompt = String.format(PROMPT_TEMPLATE, retrievedText, question);

        // 3️⃣ Call the LLM via Ollama
        return chatClient.chat(prompt);
    }
}